org: wstaroc
app: petstore
service: petstore

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-1

functions:
  verifyToken:
    handler: auth/verify.handler
#  events:
#      - cloudWatchLog: '/aws/lambda/verifyToken'

  getpets:
    handler: handlers/getPets.handler
    events:
      - http:
          path: pets
          method: get
          authorizer: verifyToken